+ module unload mvapich2_ib/2.3.2
++ /usr/bin/modulecmd bash unload mvapich2_ib/2.3.2
+ eval LD_LIBRARY_PATH=/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/../compiler/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.4 ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=intel/2018.1.163' ';export' 'LOADEDMODULES;PATH=/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin' ';export' 'PATH;_LMFILES_=/opt/modulefiles/compilers/intel/2018.1.163' ';export' '_LMFILES_;unset' 'MPIHOME;'
++ LD_LIBRARY_PATH=/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/../compiler/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.4
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=intel/2018.1.163
++ export LOADEDMODULES
++ PATH=/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
++ export PATH
++ _LMFILES_=/opt/modulefiles/compilers/intel/2018.1.163
++ export _LMFILES_
++ unset MPIHOME
+ module load openmpi_ib/3.1.4
++ /usr/bin/modulecmd bash load openmpi_ib/3.1.4
+ eval LD_LIBRARY_PATH=/opt/openmpi/intel/ib/lib:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/../compiler/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.4 ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=intel/2018.1.163:openmpi_ib/3.1.4' ';export' 'LOADEDMODULES;MPIHOME=/opt/openmpi/intel/ib' ';export' 'MPIHOME;OMPI_MCA_mpi_cuda_support=0' ';export' 'OMPI_MCA_mpi_cuda_support;PATH=/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin' ';export' 'PATH;_LMFILES_=/opt/modulefiles/compilers/intel/2018.1.163:/opt/modulefiles/mpi/openmpi_ib/3.1.4' ';export' '_LMFILES_;'
++ LD_LIBRARY_PATH=/opt/openmpi/intel/ib/lib:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/../compiler/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.4
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=intel/2018.1.163:openmpi_ib/3.1.4
++ export LOADEDMODULES
++ MPIHOME=/opt/openmpi/intel/ib
++ export MPIHOME
++ OMPI_MCA_mpi_cuda_support=0
++ export OMPI_MCA_mpi_cuda_support
++ PATH=/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
++ export PATH
++ _LMFILES_=/opt/modulefiles/compilers/intel/2018.1.163:/opt/modulefiles/mpi/openmpi_ib/3.1.4
++ export _LMFILES_
+ module load hdf5/1.10.3
++ /usr/bin/modulecmd bash load hdf5/1.10.3
+ eval HDF5HOME=/opt/hdf5/1.10.3/intel/openmpi_ib ';export' 'HDF5HOME;LD_LIBRARY_PATH=/opt/hdf5/1.10.3/intel/openmpi_ib/lib:/opt/openmpi/intel/ib/lib:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/../compiler/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.4' ';export' 'LD_LIBRARY_PATH;LIBPATH=/opt/hdf5/1.10.3/intel/openmpi_ib/lib' ';export' 'LIBPATH;LOADEDMODULES=intel/2018.1.163:openmpi_ib/3.1.4:hdf5/1.10.3' ';export' 'LOADEDMODULES;PATH=/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin' ';export' 'PATH;_LMFILES_=/opt/modulefiles/compilers/intel/2018.1.163:/opt/modulefiles/mpi/openmpi_ib/3.1.4:/opt/modulefiles/applications/hdf5/1.10.3' ';export' '_LMFILES_;'
++ HDF5HOME=/opt/hdf5/1.10.3/intel/openmpi_ib
++ export HDF5HOME
++ LD_LIBRARY_PATH=/opt/hdf5/1.10.3/intel/openmpi_ib/lib:/opt/openmpi/intel/ib/lib:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/../compiler/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.4
++ export LD_LIBRARY_PATH
++ LIBPATH=/opt/hdf5/1.10.3/intel/openmpi_ib/lib
++ export LIBPATH
++ LOADEDMODULES=intel/2018.1.163:openmpi_ib/3.1.4:hdf5/1.10.3
++ export LOADEDMODULES
++ PATH=/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
++ export PATH
++ _LMFILES_=/opt/modulefiles/compilers/intel/2018.1.163:/opt/modulefiles/mpi/openmpi_ib/3.1.4:/opt/modulefiles/applications/hdf5/1.10.3
++ export _LMFILES_
+ source activate mda8
++ _CONDA_ROOT=/home/edisj/anaconda3
++ . /home/edisj/anaconda3/etc/profile.d/conda.sh
+++ export CONDA_EXE=/home/edisj/anaconda3/bin/conda
+++ CONDA_EXE=/home/edisj/anaconda3/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/home/edisj/anaconda3/bin/python
+++ CONDA_PYTHON_EXE=/home/edisj/anaconda3/bin/python
+++ '[' -z x ']'
++ conda activate mda8
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate mda8
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
++ CONDA_INTERNAL_OLDPATH=/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
++ __add_sys_prefix_to_path
++ '[' -n '' ']'
+++ dirname /home/edisj/anaconda3/bin/conda
++ SYSP=/home/edisj/anaconda3/bin
+++ dirname /home/edisj/anaconda3/bin
++ SYSP=/home/edisj/anaconda3
++ '[' -n '' ']'
++ PATH=/home/edisj/anaconda3/bin:/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
++ export PATH
+++ PS1=
+++ /home/edisj/anaconda3/bin/conda shell.posix activate mda8
++ ask_conda='PS1='\''(mda8) '\''
export PATH='\''/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/envs/mda8/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin'\''
export CONDA_PREFIX='\''/home/edisj/anaconda3/envs/mda8'\''
export CONDA_SHLVL='\''2'\''
export CONDA_DEFAULT_ENV='\''mda8'\''
export CONDA_PROMPT_MODIFIER='\''(mda8) '\''
export CONDA_EXE='\''/home/edisj/anaconda3/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/home/edisj/anaconda3/bin/python'\''
export CONDA_PREFIX_1='\''/home/edisj/anaconda3'\'''
++ rc=0
++ PATH=/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
++ eval 'PS1='\''(mda8) '\''
export PATH='\''/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/envs/mda8/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin'\''
export CONDA_PREFIX='\''/home/edisj/anaconda3/envs/mda8'\''
export CONDA_SHLVL='\''2'\''
export CONDA_DEFAULT_ENV='\''mda8'\''
export CONDA_PROMPT_MODIFIER='\''(mda8) '\''
export CONDA_EXE='\''/home/edisj/anaconda3/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/home/edisj/anaconda3/bin/python'\''
export CONDA_PREFIX_1='\''/home/edisj/anaconda3'\'''
+++ PS1='(mda8) '
+++ export PATH=/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/envs/mda8/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
+++ PATH=/opt/hdf5/1.10.3/intel/openmpi_ib/bin:/opt/openmpi/intel/ib/bin:/home/edisj/anaconda3/envs/mda8/bin:/home/edisj/anaconda3/condabin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/edisj/bin
+++ export CONDA_PREFIX=/home/edisj/anaconda3/envs/mda8
+++ CONDA_PREFIX=/home/edisj/anaconda3/envs/mda8
+++ export CONDA_SHLVL=2
+++ CONDA_SHLVL=2
+++ export CONDA_DEFAULT_ENV=mda8
+++ CONDA_DEFAULT_ENV=mda8
+++ export 'CONDA_PROMPT_MODIFIER=(mda8) '
+++ CONDA_PROMPT_MODIFIER='(mda8) '
+++ export CONDA_EXE=/home/edisj/anaconda3/bin/conda
+++ CONDA_EXE=/home/edisj/anaconda3/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/home/edisj/anaconda3/bin/python
+++ CONDA_PYTHON_EXE=/home/edisj/anaconda3/bin/python
+++ export CONDA_PREFIX_1=/home/edisj/anaconda3
+++ CONDA_PREFIX_1=/home/edisj/anaconda3
++ '[' 0 '!=' 0 ']'
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ testdir=/oasis/scratch/comet/edisj/temp_project/benchmarking/38489237
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ ibrun -np 84 python -W ignore /oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py /oasis/scratch/comet/edisj/temp_project/benchmarking/38489237/small_top.pdb /oasis/scratch/comet/edisj/temp_project/benchmarking/38489237/small_traj.h5md run3/4node_2
IBRUN WARNING: Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Traceback (most recent call last):
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 203, in <module>
    times_array, rmsd_array = benchmark(topology, trajectory)
  File "/oasis/projects/nsf/azs119/edisj/Comet/benchmarks/Khosh_comparison/scripts/benchmark.py", line 57, in benchmark
    rmsd_array[i] = rmsd(u.trajectory.ts.positions.positions, x_ref, superposition=True)
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2165, in __del__
  File "/home/edisj/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 978, in close
  File "/home/edisj/anaconda3/envs/mda8/lib/python3.6/site-packages/h5py/_hl/files.py", line 445, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24999] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:25000] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:25002] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00677] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:25003] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24994] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:25001] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03651] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00674] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00683] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00675] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00686] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24991] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28755] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28752] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28751] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28750] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00679] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00678] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24995] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24993] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03649] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03645] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03638] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03643] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00695] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00676] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00681] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24992] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24983] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24997] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24998] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24996] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00689] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24988] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24984] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-49.sdsc.edu:00690] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24990] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24989] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24986] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24987] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-71.sdsc.edu:24985] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28754] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28758] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28759] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28756] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28753] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28761] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-70.sdsc.edu:28749] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03640] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03647] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03653] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03650] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03646] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03644] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03634] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_File_close() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[comet-06-51.sdsc.edu:03636] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
orterun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[51172,1],80]
  Exit code:    1
--------------------------------------------------------------------------

real	0m10.992s
user	0m33.504s
sys	0m6.469s
+ rm -r /oasis/scratch/comet/edisj/temp_project/benchmarking/38489237
